version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./cache:/var/www/html/cache
      - ./logs:/var/www/html/logs
      - ./packages:/var/www/html/packages
      - ./package-assets:/var/www/html/package-assets
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: 